# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3.5'

services:
  spark:
    image: bitnami/spark:3
    #image: bde2020/spark-master:3.0.0-hadoop3.2
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
      - '7077:7077'
    networks:
      - kafkanet
  spark-worker:
    #image: bitnami/spark-worker:3
    image: bde2020/spark-worker:3.0.0-hadoop3.2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    networks:
      - kafkanet


networks:
  kafkanet:
    name: kafka-network
    external: true
